services:
  traefik:
    image: traefik:3
    container_name: traefik
    restart: always
    networks:
      mailserver:
        ipv4_address: 172.19.0.2
      monitor:
    ports:
      - 80:80
      - 443:443
      - 25:25
      - 465:465
      - 587:587
      - 993:993
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./acme:/etc/certs
  

  traefik-certs-dumper:
    image: ghcr.io/kereis/traefik-certs-dumper:latest
    container_name: traefik-certs-dumper
    restart: always
    depends_on:
      - traefik
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./acme:/traefik:ro
      - ./certs:/output

networks:
  mailserver:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
  monitor:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16