services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    restart: always
    volumes:
      - ./data:/app/data
    labels:
      - traefik.enable=true

      - traefik.http.routers.uptime-kuma.rule=Host(`montior.benkner-it.com`)
      - traefik.http.routers.uptime-kuma.entrypoints=https
      - traefik.http.routers.uptime-kuma.service=uptime-kuma
      - traefik.http.services.uptime-kuma.loadbalancer.server.port=3001
