services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    restart: always
    container_name: uptime-kuma
    networks:
      - proxy 

    volumes:
      - ./data:/app/data
    labels:
      - traefik.enable=true

      - traefik.http.routers.uptime-kuma.rule=Host(`montior.benkner-it.com`)
      - traefik.http.routers.uptime-kuma.entrypoints=https
      - traefik.http.services.uptime-kuma.loadbalancer.server.port=3001

networks:
  proxy:
    name: traefik_proxy
    external: true