# to add

certificate.default.cert = "%{file:/data/certs/mail.benkner-it.com/cert.pem}%"
certificate.default.default = true
certificate.default.private-key = "%{file:/data/certs/mail.benkner-it.com/key.pem}%"

http.hsts = true
http.permissive-cors = false
http.url = "protocol + '://' + config_get('server.hostname') + ':' + local_port"
http.use-x-forwarded = true

server.listener.imaptls.proxy.override = true
server.listener.imaptls.proxy.trusted-networks.0 = "172.19.0.2"
server.listener.imaptls.proxy.trusted-networks.1 = "172.19.0.0/16"


server.listener.smtp.proxy.override = true
server.listener.smtp.proxy.trusted-networks.0 = "172.19.0.2"
server.listener.smtp.proxy.trusted-networks.1 = "172.19.0.0/16"

server.listener.submissions.proxy.override = true
server.listener.submissions.proxy.trusted-networks.0 = "172.19.0.2"
server.listener.submissions.proxy.trusted-networks.1 = "172.19.0.0/16"


config.local-keys.00 = "store.*"
config.local-keys.01 = "directory.*"
config.local-keys.02 = "tracer.*"
config.local-keys.03 = "!server.blocked-ip.*"
config.local-keys.04 = "!server.allowed-ip.*"
config.local-keys.05 = "server.*"
config.local-keys.06 = "config.local-keys.*"
config.local-keys.07 = "certificate.*"
config.local-keys.08 = "cluster.*"
config.local-keys.09 = "storage.data"
config.local-keys.10 = "storage.blob"
config.local-keys.11 = "storage.lookup"
config.local-keys.12 = "storage.fts"
config.local-keys.13 = "storage.directory"
config.local-keys.14 = "authentication.fallback-admin.*"
config.local-keys.15 = "enterprise.license-key"
config.local-keys.16 = "http.*"