services:
  mailserver:
    image: stalwartlabs/stalwart:latest
    container_name: mailserver
    restart: always
    hostname: mail.example.com
    networks:
      proxy:
        ipv4_address: 172.19.0.5
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/mail-server/traefik/certs:/data/certs:ro
      - ./data:/opt/stalwart
    labels:
      - traefik.enable=true

      - traefik.http.routers.mailserver.rule=Host(`mail.benkner-it.com`) || Host(`autodiscover.benkner-it.com`) || Host(`autoconfig.benkner-it.com`) || Host(`mta-sts.benkner-it.com`)
      - traefik.http.routers.mailserver.entrypoints=https
      - traefik.http.routers.mailserver.service=mailserver
      - traefik.http.services.mailserver.loadbalancer.server.port=8080

      - traefik.tcp.routers.smtp.rule=HostSNI(`*`)
      - traefik.tcp.routers.smtp.entrypoints=smtp
      - traefik.tcp.routers.smtp.service=smtp
      - traefik.tcp.services.smtp.loadbalancer.server.port=25
      - traefik.tcp.services.smtp.loadbalancer.proxyProtocol.version=2

      # - traefik.tcp.routers.jmap.rule=HostSNI(`*`)
      # - traefik.tcp.routers.jmap.tls.passthrough=true
      # - traefik.tcp.routers.jmap.entrypoints=https
      # - traefik.tcp.routers.jmap.service=jmap
      # - traefik.tcp.services.jmap.loadbalancer.server.port=443
      # - traefik.tcp.services.jmap.loadbalancer.proxyProtocol.version=2

      - traefik.tcp.routers.smtps.rule=HostSNI(`*`)
      - traefik.tcp.routers.smtps.tls.passthrough=true
      - traefik.tcp.routers.smtps.entrypoints=smtps
      - traefik.tcp.routers.smtps.service=smtps
      - traefik.tcp.services.smtps.loadbalancer.server.port=465
      - traefik.tcp.services.smtps.loadbalancer.proxyProtocol.version=2

      - traefik.tcp.routers.imaps.rule=HostSNI(`*`)
      - traefik.tcp.routers.imaps.tls.passthrough=true
      - traefik.tcp.routers.imaps.entrypoints=imaps
      - traefik.tcp.routers.imaps.service=imaps
      - traefik.tcp.services.imaps.loadbalancer.server.port=993
      - traefik.tcp.services.imaps.loadbalancer.proxyProtocol.version=2

networks:
  proxy:
    name: traefik_proxy
    external: true